include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: ignore
  exclude:
    - build/**

linter:
  rules:
    - prefer_final_locals
