// Requirement traceability gate.
//
// The cahier des charges asks that every requirement be "verified by a named test"
// (§14.1) and that every FR be "tagged and traceable" (G1 exit criteria). A spreadsheet
// cannot enforce that; this can.
//
// Three checks, all of which fail the build:
//
//   1. A requirement whose status says it is done must be named in a test file. A green
//      test suite that tests something other than the requirement is the failure mode
//      this exists to catch.
//   2. M1 must import no platform library. "Pure Dart, no platform APIs" is what makes
//      the interpreter's semantics identical on Android, iOS, desktop and WASM, and
//      therefore what makes a grading verdict portable (§11.1).
//   3. Every requirement id referenced in code must exist in the register. A reference to
//      FR-M1-99 means someone is building against a requirement nobody agreed.
//
// Run: dart tools/trace_check.dart
//
// It is deliberately dependency-free so CI can run it before any `pub get`.

import 'dart:convert';
import 'dart:io';

final _requirementPattern = RegExp(r'\b((?:FR|NFR)-[A-Z0-9]+-\d{2})\b');

/// Libraries that would tie the language core to one platform.
const _forbiddenImports = [
  'dart:io',
  'dart:html',
  'dart:ui',
  'dart:ffi',
  'dart:js',
  'dart:js_interop',
  'package:flutter/',
];

int _failures = 0;

void _fail(String message) {
  stderr.writeln('  FAIL  $message');
  _failures++;
}

void main() {
  final root = Directory.current;
  final registerFile = File('${root.path}/spec/requirements.json');
  if (!registerFile.existsSync()) {
    stderr.writeln('spec/requirements.json is missing — run tools/gen_spec.py');
    exit(2);
  }

  final register = jsonDecode(registerFile.readAsStringSync()) as Map<String, Object?>;
  final requirements = (register['requirements']! as List<Object?>)
      .cast<Map<String, Object?>>();
  final known = {for (final r in requirements) r['id']! as String};

  final testFiles = _dartFiles('${root.path}/packages', within: 'test');
  final libFiles = _dartFiles('${root.path}/packages', within: 'lib');

  // --- 1. done requirements are named in a test ------------------------------------------
  final referencedInTests = <String, List<String>>{};
  for (final file in testFiles) {
    for (final match in _requirementPattern.allMatches(file.readAsStringSync())) {
      referencedInTests
          .putIfAbsent(match.group(1)!, () => [])
          .add(_relative(file.path, root.path));
    }
  }

  final done = requirements.where((r) => _isDone(r['status'] as String?)).toList();
  for (final requirement in done) {
    final id = requirement['id']! as String;
    if (!referencedInTests.containsKey(id)) {
      _fail('$id is marked "${requirement['status']}" but no test names it');
    }
  }

  // --- 2. the language core stays pure ---------------------------------------------------
  for (final file in libFiles) {
    if (!file.path.contains('/kodo_lang/')) continue;
    final source = file.readAsStringSync();
    for (final forbidden in _forbiddenImports) {
      if (RegExp("import\\s+'${RegExp.escape(forbidden)}").hasMatch(source)) {
        _fail('${_relative(file.path, root.path)} imports $forbidden — M1 must stay '
            'platform-free, or grading stops being portable');
      }
    }
  }

  // --- 3. no references to requirements nobody agreed ------------------------------------
  for (final file in [...testFiles, ...libFiles]) {
    for (final match in _requirementPattern.allMatches(file.readAsStringSync())) {
      final id = match.group(1)!;
      if (!known.contains(id)) {
        _fail('${_relative(file.path, root.path)} references $id, '
            'which is not in the requirement register');
      }
    }
  }

  // --- report ----------------------------------------------------------------------------
  final byModule = <String, List<Map<String, Object?>>>{};
  for (final requirement in requirements) {
    byModule.putIfAbsent(requirement['moduleId']! as String, () => []).add(requirement);
  }

  final report = StringBuffer()
    ..writeln('# Requirement traceability')
    ..writeln()
    ..writeln('Generated by `tools/trace_check.dart`. A requirement is traceable when a '
        'test names it.')
    ..writeln()
    ..writeln('| Module | Requirements | Done | Named by a test |')
    ..writeln('| --- | ---: | ---: | ---: |');

  final moduleIds = byModule.keys.toList()..sort(_moduleOrder);
  for (final moduleId in moduleIds) {
    final rows = byModule[moduleId]!;
    final doneCount = rows.where((r) => _isDone(r['status'] as String?)).length;
    final traced =
        rows.where((r) => referencedInTests.containsKey(r['id'])).length;
    report.writeln('| $moduleId | ${rows.length} | $doneCount | $traced |');
  }

  report
    ..writeln()
    ..writeln('## Requirements named by a test')
    ..writeln()
    ..writeln('| Requirement | Status | Named in |')
    ..writeln('| --- | --- | --- |');
  final tracedIds = referencedInTests.keys.toList()..sort();
  for (final id in tracedIds) {
    final requirement = requirements.firstWhere((r) => r['id'] == id,
        orElse: () => <String, Object?>{'status': '—'});
    final files = referencedInTests[id]!.toSet().toList()..sort();
    report.writeln('| $id | ${requirement['status']} | ${files.join(', ')} |');
  }

  final out = File('${root.path}/build/traceability.md');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(report.toString());

  stdout.writeln('traceability: ${requirements.length} requirements, '
      '${done.length} marked done, ${referencedInTests.length} named by a test');
  stdout.writeln('report: build/traceability.md');

  if (_failures > 0) {
    stderr.writeln('\n$_failures traceability failure(s)');
    exit(1);
  }
  stdout.writeln('OK');
}

bool _isDone(String? status) {
  final s = (status ?? '').toLowerCase();
  return s == 'done' || s == 'conforme' || s == 'implemented';
}

int _moduleOrder(String a, String b) {
  final aNum = int.tryParse(a.replaceFirst('M', ''));
  final bNum = int.tryParse(b.replaceFirst('M', ''));
  if (aNum != null && bNum != null) return aNum.compareTo(bNum);
  if (aNum != null) return -1;
  if (bNum != null) return 1;
  return a.compareTo(b);
}

String _relative(String path, String root) =>
    path.startsWith(root) ? path.substring(root.length + 1) : path;

List<File> _dartFiles(String path, {required String within}) {
  final directory = Directory(path);
  if (!directory.existsSync()) return [];
  return directory
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .where((f) => f.path.contains('/$within/'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
}
